package auth

import "testing"

func TestIdentityV3PasswordRoundTrip(t *testing.T) {
	hash, err := hashPassword("Correct-Horse-7-Battery")
	if err != nil {
		t.Fatal(err)
	}
	if !verifyPassword(hash, "Correct-Horse-7-Battery") || verifyPassword(hash, "incorrect") {
		t.Fatal("Identity V3 password verification failed")
	}
}

func TestVerifyKnownAspNetIdentityV3Hash(t *testing.T) {
	// Generated by PasswordHasher<ApplicationUser> using IdentityV3 compatibility mode.
	const hash = "AQAAAAIAAYagAAAAEOpDQh8uKduMC2BA3YxLz9An2HSKonwpqpmFuAV4pQCSCdsJg2A+9k5nkCUx6Y0Qeg=="
	if !verifyPassword(hash, "Flare-Test-Password-9!") {
		t.Fatal("Go verifier rejected an ASP.NET Identity V3 password hash")
	}
}

func TestPasswordPolicy(t *testing.T) {
	if validatePassword("Correct-Horse-7-Battery") != nil {
		t.Fatal("strong password was rejected")
	}
	if validatePassword("onlylowercase") == nil {
		t.Fatal("weak password was accepted")
	}
}
