CREATE TABLE IF NOT EXISTS "AuditEvents" (
    "Id" uuid PRIMARY KEY,
    "UserId" uuid NULL,
    "Actor" varchar(254) NULL,
    "Action" varchar(100) NOT NULL,
    "Target" varchar(256) NOT NULL,
    "Timestamp" timestamptz NOT NULL,
    "Result" integer NOT NULL,
    "CorrelationId" varchar(128) NOT NULL,
    "Detail" varchar(1000) NULL
);

CREATE TABLE IF NOT EXISTS "InfrastructureEvents" (
    "Id" uuid PRIMARY KEY,
    "Action" varchar(100) NOT NULL,
    "Target" varchar(256) NOT NULL,
    "Timestamp" timestamptz NOT NULL,
    "Result" integer NOT NULL,
    "Detail" varchar(1000) NULL
);

CREATE TABLE IF NOT EXISTS "MetricSamples" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Timestamp" timestamptz NOT NULL,
    "CpuPercent" double precision NULL,
    "MemoryPercent" double precision NULL
);

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id" uuid PRIMARY KEY,
    "Name" varchar(256) NULL,
    "NormalizedName" varchar(256) NULL,
    "ConcurrencyStamp" text NULL
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" uuid PRIMARY KEY,
    "CreatedAt" timestamptz NOT NULL,
    "UserName" varchar(256) NULL,
    "NormalizedUserName" varchar(256) NULL,
    "Email" varchar(256) NULL,
    "NormalizedEmail" varchar(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamptz NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" uuid PRIMARY KEY,
    "TokenHash" varchar(64) NOT NULL,
    "FamilyId" uuid NOT NULL,
    "UserId" uuid NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAt" timestamptz NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    "RevokedAt" timestamptz NULL,
    "ReplacedById" uuid NULL,
    "CreatedByIp" varchar(64) NULL,
    "RevokedByIp" varchar(64) NULL
);

CREATE TABLE IF NOT EXISTS "UserRoles" (
    "UserId" uuid NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "RoleId" uuid NOT NULL REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);

CREATE INDEX IF NOT EXISTS "IX_AuditEvents_Timestamp" ON "AuditEvents" ("Timestamp");
CREATE INDEX IF NOT EXISTS "IX_InfrastructureEvents_Timestamp" ON "InfrastructureEvents" ("Timestamp");
CREATE INDEX IF NOT EXISTS "IX_MetricSamples_Timestamp" ON "MetricSamples" ("Timestamp");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId_FamilyId" ON "RefreshTokens" ("UserId", "FamilyId");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "Roles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "Users" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "Users" ("NormalizedUserName");
